package com.gabriel2305.parser;

public enum FragmentParserState {
    IDLE,
    ID_DECLARATION,
    ID_DECLARED,
    TYPE_DECLARATION,
    TYPE_DECLARED,
    NODE_PARAMS_DECLARATION,

    NODE_PARAM_TRANSITION,
    NODE_TEXT_DECLARATION,
    NODE_TEXT_DECLARED,
    NODE_GOTO_DECLARATION,
    NODE_GOTO_DECLARED,
}
