package com.gabriel2305.parser;

public enum FragmentType {
    OPENING_PARENTHESIS,
    CLOSING_PARENTHESIS,
    OPENING_SQUARE_BRACKET,
    CLOSING_SQUARE_BRACKET,
    OPENING_CURLY_BRACE,
    CLOSING_CURLY_BRACE,
    OPENING_QUOTES,
    CLOSING_QUOTES,
    NODE_ID,
    NODE_TYPE,
    NODE_TEXT,
    COMMA,
}
