package com.gabriel2305.parser;

public enum FragmentParserState {
    IDLE,
    ID_DECLARATION,
    ID_DECLARED,
    TYPE_DECLARATION,
    TYPE_DECLARED,
    NODE_PARAMS_DECLARATION,
    NODE_PARAM_TRANSITION,
    NODE_CREATED,

    TEXT_NODE_TEXT_DECLARATION,
    TEXT_NODE_TEXT_DECLARED,
    TEXT_NODE_GOTO_DECLARATION,
    TEXT_NODE_GOTO_DECLARED,
}
